name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
# TODO make the changelog actually be built
#      - name: Build Changelog
#        id: build_changelog
#        uses: mikepenz/release-changelog-builder-action@v1
#        with:
#          commitMode: true
#          token: ${{ github.token }}
      - name: Setup ENV
        run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Jar with Gradle
        id: publish_release_assets
        run: ./gradlew buildAll -Pversion=${{ env.TAG }}
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref }}
          name: Release ${{ env.TAG }}
          # body: ${{steps.build_changelog.outputs.changelog}}
          artifactErrorsFailBuild: true
          artifacts: 'build/libs/**.jar'
          generateReleaseNotes: true
